package com.lance.model.eo;


import com.zngh.platform.front.core.model.BaseEntityImpl;

import java.math.BigDecimal;

import oracle.jbo.Key;
import oracle.jbo.RowInconsistentException;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue May 26 15:15:57 CST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PostJobDiscussEOImpl extends BaseEntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Uuid,
        PostJobId,
        Content,
        IsApply,
        Postform,
        HourlyPay,
        FixedPayMin,
        FixedPayMax,
        SignBy,
        WeeklyHours,
        EnteryDate,
        ParentDiscussId,
        CreateBy,
        CreateOn,
        ModifyBy,
        ModifyOn,
        Version,
        Status,
        StatusLog;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int UUID = AttributesEnum.Uuid.index();
    public static final int POSTJOBID = AttributesEnum.PostJobId.index();
    public static final int CONTENT = AttributesEnum.Content.index();
    public static final int ISAPPLY = AttributesEnum.IsApply.index();
    public static final int POSTFORM = AttributesEnum.Postform.index();
    public static final int HOURLYPAY = AttributesEnum.HourlyPay.index();
    public static final int FIXEDPAYMIN = AttributesEnum.FixedPayMin.index();
    public static final int FIXEDPAYMAX = AttributesEnum.FixedPayMax.index();
    public static final int SIGNBY = AttributesEnum.SignBy.index();
    public static final int WEEKLYHOURS = AttributesEnum.WeeklyHours.index();
    public static final int ENTERYDATE = AttributesEnum.EnteryDate.index();
    public static final int PARENTDISCUSSID = AttributesEnum.ParentDiscussId.index();
    public static final int CREATEBY = AttributesEnum.CreateBy.index();
    public static final int CREATEON = AttributesEnum.CreateOn.index();
    public static final int MODIFYBY = AttributesEnum.ModifyBy.index();
    public static final int MODIFYON = AttributesEnum.ModifyOn.index();
    public static final int VERSION = AttributesEnum.Version.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int STATUSLOG = AttributesEnum.StatusLog.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PostJobDiscussEOImpl() {
    }

    /**
     * Gets the attribute value for Uuid, using the alias name Uuid.
     * @return the value of Uuid
     */
    public String getUuid() {
        return (String) getAttributeInternal(UUID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Uuid.
     * @param value value to set the Uuid
     */
    public void setUuid(String value) {
        setAttributeInternal(UUID, value);
    }

    /**
     * Gets the attribute value for PostJobId, using the alias name PostJobId.
     * @return the value of PostJobId
     */
    public String getPostJobId() {
        return (String) getAttributeInternal(POSTJOBID);
    }

    /**
     * Sets <code>value</code> as the attribute value for PostJobId.
     * @param value value to set the PostJobId
     */
    public void setPostJobId(String value) {
        setAttributeInternal(POSTJOBID, value);
    }

    /**
     * Gets the attribute value for Content, using the alias name Content.
     * @return the value of Content
     */
    public String getContent() {
        return (String) getAttributeInternal(CONTENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for Content.
     * @param value value to set the Content
     */
    public void setContent(String value) {
        setAttributeInternal(CONTENT, value);
    }

    /**
     * Gets the attribute value for IsApply, using the alias name IsApply.
     * @return the value of IsApply
     */
    public String getIsApply() {
        return (String) getAttributeInternal(ISAPPLY);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsApply.
     * @param value value to set the IsApply
     */
    public void setIsApply(String value) {
        setAttributeInternal(ISAPPLY, value);
    }

    /**
     * Gets the attribute value for Postform, using the alias name Postform.
     * @return the value of Postform
     */
    public String getPostform() {
        return (String) getAttributeInternal(POSTFORM);
    }

    /**
     * Sets <code>value</code> as the attribute value for Postform.
     * @param value value to set the Postform
     */
    public void setPostform(String value) {
        setAttributeInternal(POSTFORM, value);
    }

    /**
     * Gets the attribute value for HourlyPay, using the alias name HourlyPay.
     * @return the value of HourlyPay
     */
    public BigDecimal getHourlyPay() {
        return (BigDecimal) getAttributeInternal(HOURLYPAY);
    }

    /**
     * Sets <code>value</code> as the attribute value for HourlyPay.
     * @param value value to set the HourlyPay
     */
    public void setHourlyPay(BigDecimal value) {
        setAttributeInternal(HOURLYPAY, value);
    }

    /**
     * Gets the attribute value for FixedPayMin, using the alias name FixedPayMin.
     * @return the value of FixedPayMin
     */
    public BigDecimal getFixedPayMin() {
        return (BigDecimal) getAttributeInternal(FIXEDPAYMIN);
    }

    /**
     * Sets <code>value</code> as the attribute value for FixedPayMin.
     * @param value value to set the FixedPayMin
     */
    public void setFixedPayMin(BigDecimal value) {
        setAttributeInternal(FIXEDPAYMIN, value);
    }

    /**
     * Gets the attribute value for FixedPayMax, using the alias name FixedPayMax.
     * @return the value of FixedPayMax
     */
    public BigDecimal getFixedPayMax() {
        return (BigDecimal) getAttributeInternal(FIXEDPAYMAX);
    }

    /**
     * Sets <code>value</code> as the attribute value for FixedPayMax.
     * @param value value to set the FixedPayMax
     */
    public void setFixedPayMax(BigDecimal value) {
        setAttributeInternal(FIXEDPAYMAX, value);
    }

    /**
     * Gets the attribute value for SignBy, using the alias name SignBy.
     * @return the value of SignBy
     */
    public String getSignBy() {
        return (String) getAttributeInternal(SIGNBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for SignBy.
     * @param value value to set the SignBy
     */
    public void setSignBy(String value) {
        setAttributeInternal(SIGNBY, value);
    }

    /**
     * Gets the attribute value for WeeklyHours, using the alias name WeeklyHours.
     * @return the value of WeeklyHours
     */
    public Integer getWeeklyHours() {
        return (Integer) getAttributeInternal(WEEKLYHOURS);
    }

    /**
     * Sets <code>value</code> as the attribute value for WeeklyHours.
     * @param value value to set the WeeklyHours
     */
    public void setWeeklyHours(Integer value) {
        setAttributeInternal(WEEKLYHOURS, value);
    }

    /**
     * Gets the attribute value for EnteryDate, using the alias name EnteryDate.
     * @return the value of EnteryDate
     */
    public Date getEnteryDate() {
        return (Date) getAttributeInternal(ENTERYDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for EnteryDate.
     * @param value value to set the EnteryDate
     */
    public void setEnteryDate(Date value) {
        setAttributeInternal(ENTERYDATE, value);
    }

    /**
     * Gets the attribute value for ParentDiscussId, using the alias name ParentDiscussId.
     * @return the value of ParentDiscussId
     */
    public String getParentDiscussId() {
        return (String) getAttributeInternal(PARENTDISCUSSID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ParentDiscussId.
     * @param value value to set the ParentDiscussId
     */
    public void setParentDiscussId(String value) {
        setAttributeInternal(PARENTDISCUSSID, value);
    }

    /**
     * Gets the attribute value for CreateBy, using the alias name CreateBy.
     * @return the value of CreateBy
     */
    public String getCreateBy() {
        return (String) getAttributeInternal(CREATEBY);
    }

    /**
     * Gets the attribute value for CreateOn, using the alias name CreateOn.
     * @return the value of CreateOn
     */
    public Date getCreateOn() {
        return (Date) getAttributeInternal(CREATEON);
    }

    /**
     * Gets the attribute value for ModifyBy, using the alias name ModifyBy.
     * @return the value of ModifyBy
     */
    public String getModifyBy() {
        return (String) getAttributeInternal(MODIFYBY);
    }

    /**
     * Gets the attribute value for ModifyOn, using the alias name ModifyOn.
     * @return the value of ModifyOn
     */
    public Date getModifyOn() {
        return (Date) getAttributeInternal(MODIFYON);
    }

    /**
     * Gets the attribute value for Version, using the alias name Version.
     * @return the value of Version
     */
    public Number getVersion() {
        return (Number) getAttributeInternal(VERSION);
    }

    /**
     * Gets the attribute value for Status, using the alias name Status.
     * @return the value of Status
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Status.
     * @param value value to set the Status
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for StatusLog, using the alias name StatusLog.
     * @return the value of StatusLog
     */
    public String getStatusLog() {
        return (String) getAttributeInternal(STATUSLOG);
    }

    /**
     * Sets <code>value</code> as the attribute value for StatusLog.
     * @param value value to set the StatusLog
     */
    public void setStatusLog(String value) {
        setAttributeInternal(STATUSLOG, value);
    }

    /**
     * @param uuid key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(String uuid) {
        return new Key(new Object[] { uuid });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("com.lance.model.eo.PostJobDiscussEO");
    }


    @Override
    public void lock() {
        try {
            super.lock();
        } catch (RowInconsistentException e) {
            refresh(REFRESH_WITH_DB_ONLY_IF_UNCHANGED | REFRESH_CONTAINEES);
            super.lock();
        }
    }
}

