package com.lance.model.eo;

import com.zngh.platform.front.core.model.BaseEntityImpl;
import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.Key;
import oracle.jbo.RowInconsistentException;
import oracle.jbo.domain.ClobDomain;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue May 26 15:18:35 CST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PostJobsEOImpl extends BaseEntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Uuid,
        Name,
        Brief,
        Attach,
        WorkSubcategory,
        Postform,
        WeeklyHours,
        FixedLocation,
        LocationDesc,
        HourlyPayMin,
        DurationMin,
        FixedPayMin,
        JobVisibility,
        AllowSearchEngines,
        WorkCategory,
        SpecificSkillA,
        SpecificSkillB,
        SpecificSkillC,
        SpecificSkillD,
        SpecificSkillE,
        SpecificSkillF,
        SpecificSkillG,
        HourlyPayMax,
        FixedPayMax,
        DurationMax,
        Status,
        PostJobDateStart,
        PostJobDateEnd,
        LocationCountry,
        LocationProvince,
        LocationCity,
        CreateBy,
        CreateOn,
        ModifyBy,
        ModifyOn,
        Version,
        StatusDesc,
        IndexSkills,
        IndexWorkCategorys,
        IndexLocation,
        LocationRegion,
        SignBy,
        IndexAllMetaInfo,
        Rank,
        RankDesc,
        ApplyCount;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int UUID = AttributesEnum.Uuid.index();
    public static final int NAME = AttributesEnum.Name.index();
    public static final int BRIEF = AttributesEnum.Brief.index();
    public static final int ATTACH = AttributesEnum.Attach.index();
    public static final int WORKSUBCATEGORY = AttributesEnum.WorkSubcategory.index();
    public static final int POSTFORM = AttributesEnum.Postform.index();
    public static final int WEEKLYHOURS = AttributesEnum.WeeklyHours.index();
    public static final int FIXEDLOCATION = AttributesEnum.FixedLocation.index();
    public static final int LOCATIONDESC = AttributesEnum.LocationDesc.index();
    public static final int HOURLYPAYMIN = AttributesEnum.HourlyPayMin.index();
    public static final int DURATIONMIN = AttributesEnum.DurationMin.index();
    public static final int FIXEDPAYMIN = AttributesEnum.FixedPayMin.index();
    public static final int JOBVISIBILITY = AttributesEnum.JobVisibility.index();
    public static final int ALLOWSEARCHENGINES = AttributesEnum.AllowSearchEngines.index();
    public static final int WORKCATEGORY = AttributesEnum.WorkCategory.index();
    public static final int SPECIFICSKILLA = AttributesEnum.SpecificSkillA.index();
    public static final int SPECIFICSKILLB = AttributesEnum.SpecificSkillB.index();
    public static final int SPECIFICSKILLC = AttributesEnum.SpecificSkillC.index();
    public static final int SPECIFICSKILLD = AttributesEnum.SpecificSkillD.index();
    public static final int SPECIFICSKILLE = AttributesEnum.SpecificSkillE.index();
    public static final int SPECIFICSKILLF = AttributesEnum.SpecificSkillF.index();
    public static final int SPECIFICSKILLG = AttributesEnum.SpecificSkillG.index();
    public static final int HOURLYPAYMAX = AttributesEnum.HourlyPayMax.index();
    public static final int FIXEDPAYMAX = AttributesEnum.FixedPayMax.index();
    public static final int DURATIONMAX = AttributesEnum.DurationMax.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int POSTJOBDATESTART = AttributesEnum.PostJobDateStart.index();
    public static final int POSTJOBDATEEND = AttributesEnum.PostJobDateEnd.index();
    public static final int LOCATIONCOUNTRY = AttributesEnum.LocationCountry.index();
    public static final int LOCATIONPROVINCE = AttributesEnum.LocationProvince.index();
    public static final int LOCATIONCITY = AttributesEnum.LocationCity.index();
    public static final int CREATEBY = AttributesEnum.CreateBy.index();
    public static final int CREATEON = AttributesEnum.CreateOn.index();
    public static final int MODIFYBY = AttributesEnum.ModifyBy.index();
    public static final int MODIFYON = AttributesEnum.ModifyOn.index();
    public static final int VERSION = AttributesEnum.Version.index();
    public static final int STATUSDESC = AttributesEnum.StatusDesc.index();
    public static final int INDEXSKILLS = AttributesEnum.IndexSkills.index();
    public static final int INDEXWORKCATEGORYS = AttributesEnum.IndexWorkCategorys.index();
    public static final int INDEXLOCATION = AttributesEnum.IndexLocation.index();
    public static final int LOCATIONREGION = AttributesEnum.LocationRegion.index();
    public static final int SIGNBY = AttributesEnum.SignBy.index();
    public static final int INDEXALLMETAINFO = AttributesEnum.IndexAllMetaInfo.index();
    public static final int RANK = AttributesEnum.Rank.index();
    public static final int RANKDESC = AttributesEnum.RankDesc.index();
    public static final int APPLYCOUNT = AttributesEnum.ApplyCount.index();

    /**
     * This is the default constructor (do not remove).
     */
    public PostJobsEOImpl() {
    }

    /**
     * Gets the attribute value for Uuid, using the alias name Uuid.
     * @return the value of Uuid
     */
    public String getUuid() {
        return (String) getAttributeInternal(UUID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Uuid.
     * @param value value to set the Uuid
     */
    public void setUuid(String value) {
        setAttributeInternal(UUID, value);
    }

    /**
     * Gets the attribute value for Name, using the alias name Name.
     * @return the value of Name
     */
    public String getName() {
        return (String) getAttributeInternal(NAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for Name.
     * @param value value to set the Name
     */
    public void setName(String value) {
        setAttributeInternal(NAME, value);
    }

    /**
     * Gets the attribute value for Brief, using the alias name Brief.
     * @return the value of Brief
     */
    public String getBrief() {
        return (String) getAttributeInternal(BRIEF);
    }

    /**
     * Sets <code>value</code> as the attribute value for Brief.
     * @param value value to set the Brief
     */
    public void setBrief(String value) {
        setAttributeInternal(BRIEF, value);
    }

    /**
     * Gets the attribute value for Attach, using the alias name Attach.
     * @return the value of Attach
     */
    public String getAttach() {
        return (String) getAttributeInternal(ATTACH);
    }

    /**
     * Sets <code>value</code> as the attribute value for Attach.
     * @param value value to set the Attach
     */
    public void setAttach(String value) {
        setAttributeInternal(ATTACH, value);
    }

    /**
     * Gets the attribute value for WorkSubcategory, using the alias name WorkSubcategory.
     * @return the value of WorkSubcategory
     */
    public String getWorkSubcategory() {
        return (String) getAttributeInternal(WORKSUBCATEGORY);
    }

    /**
     * Sets <code>value</code> as the attribute value for WorkSubcategory.
     * @param value value to set the WorkSubcategory
     */
    public void setWorkSubcategory(String value) {
        setAttributeInternal(WORKSUBCATEGORY, value);
    }

    /**
     * Gets the attribute value for Postform, using the alias name Postform.
     * @return the value of Postform
     */
    public String getPostform() {
        return (String) getAttributeInternal(POSTFORM);
    }

    /**
     * Sets <code>value</code> as the attribute value for Postform.
     * @param value value to set the Postform
     */
    public void setPostform(String value) {
        setAttributeInternal(POSTFORM, value);
    }

    /**
     * Gets the attribute value for WeeklyHours, using the alias name WeeklyHours.
     * @return the value of WeeklyHours
     */
    public Number getWeeklyHours() {
        return (Number) getAttributeInternal(WEEKLYHOURS);
    }

    /**
     * Sets <code>value</code> as the attribute value for WeeklyHours.
     * @param value value to set the WeeklyHours
     */
    public void setWeeklyHours(Number value) {
        setAttributeInternal(WEEKLYHOURS, value);
    }

    /**
     * Gets the attribute value for FixedLocation, using the alias name FixedLocation.
     * @return the value of FixedLocation
     */
    public String getFixedLocation() {
        return (String) getAttributeInternal(FIXEDLOCATION);
    }

    /**
     * Sets <code>value</code> as the attribute value for FixedLocation.
     * @param value value to set the FixedLocation
     */
    public void setFixedLocation(String value) {
        setAttributeInternal(FIXEDLOCATION, value);
    }

    /**
     * Gets the attribute value for LocationDesc, using the alias name LocationDesc.
     * @return the value of LocationDesc
     */
    public String getLocationDesc() {
        return (String) getAttributeInternal(LOCATIONDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for LocationDesc.
     * @param value value to set the LocationDesc
     */
    public void setLocationDesc(String value) {
        setAttributeInternal(LOCATIONDESC, value);
    }

    /**
     * Gets the attribute value for HourlyPayMin, using the alias name HourlyPayMin.
     * @return the value of HourlyPayMin
     */
    public BigDecimal getHourlyPayMin() {
        return (BigDecimal) getAttributeInternal(HOURLYPAYMIN);
    }

    /**
     * Sets <code>value</code> as the attribute value for HourlyPayMin.
     * @param value value to set the HourlyPayMin
     */
    public void setHourlyPayMin(BigDecimal value) {
        setAttributeInternal(HOURLYPAYMIN, value);
    }

    /**
     * Gets the attribute value for DurationMin, using the alias name DurationMin.
     * @return the value of DurationMin
     */
    public BigDecimal getDurationMin() {
        return (BigDecimal) getAttributeInternal(DURATIONMIN);
    }

    /**
     * Sets <code>value</code> as the attribute value for DurationMin.
     * @param value value to set the DurationMin
     */
    public void setDurationMin(BigDecimal value) {
        setAttributeInternal(DURATIONMIN, value);
    }

    /**
     * Gets the attribute value for FixedPayMin, using the alias name FixedPayMin.
     * @return the value of FixedPayMin
     */
    public BigDecimal getFixedPayMin() {
        return (BigDecimal) getAttributeInternal(FIXEDPAYMIN);
    }

    /**
     * Sets <code>value</code> as the attribute value for FixedPayMin.
     * @param value value to set the FixedPayMin
     */
    public void setFixedPayMin(BigDecimal value) {
        setAttributeInternal(FIXEDPAYMIN, value);
    }

    /**
     * Gets the attribute value for JobVisibility, using the alias name JobVisibility.
     * @return the value of JobVisibility
     */
    public String getJobVisibility() {
        return (String) getAttributeInternal(JOBVISIBILITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for JobVisibility.
     * @param value value to set the JobVisibility
     */
    public void setJobVisibility(String value) {
        setAttributeInternal(JOBVISIBILITY, value);
    }

    /**
     * Gets the attribute value for AllowSearchEngines, using the alias name AllowSearchEngines.
     * @return the value of AllowSearchEngines
     */
    public String getAllowSearchEngines() {
        return (String) getAttributeInternal(ALLOWSEARCHENGINES);
    }

    /**
     * Sets <code>value</code> as the attribute value for AllowSearchEngines.
     * @param value value to set the AllowSearchEngines
     */
    public void setAllowSearchEngines(String value) {
        setAttributeInternal(ALLOWSEARCHENGINES, value);
    }

    /**
     * Gets the attribute value for WorkCategory, using the alias name WorkCategory.
     * @return the value of WorkCategory
     */
    public String getWorkCategory() {
        return (String) getAttributeInternal(WORKCATEGORY);
    }

    /**
     * Sets <code>value</code> as the attribute value for WorkCategory.
     * @param value value to set the WorkCategory
     */
    public void setWorkCategory(String value) {
        setAttributeInternal(WORKCATEGORY, value);
    }

    /**
     * Gets the attribute value for SpecificSkillA, using the alias name SpecificSkillA.
     * @return the value of SpecificSkillA
     */
    public String getSpecificSkillA() {
        return (String) getAttributeInternal(SPECIFICSKILLA);
    }

    /**
     * Sets <code>value</code> as the attribute value for SpecificSkillA.
     * @param value value to set the SpecificSkillA
     */
    public void setSpecificSkillA(String value) {
        setAttributeInternal(SPECIFICSKILLA, value);
    }

    /**
     * Gets the attribute value for SpecificSkillB, using the alias name SpecificSkillB.
     * @return the value of SpecificSkillB
     */
    public String getSpecificSkillB() {
        return (String) getAttributeInternal(SPECIFICSKILLB);
    }

    /**
     * Sets <code>value</code> as the attribute value for SpecificSkillB.
     * @param value value to set the SpecificSkillB
     */
    public void setSpecificSkillB(String value) {
        setAttributeInternal(SPECIFICSKILLB, value);
    }

    /**
     * Gets the attribute value for SpecificSkillC, using the alias name SpecificSkillC.
     * @return the value of SpecificSkillC
     */
    public String getSpecificSkillC() {
        return (String) getAttributeInternal(SPECIFICSKILLC);
    }

    /**
     * Sets <code>value</code> as the attribute value for SpecificSkillC.
     * @param value value to set the SpecificSkillC
     */
    public void setSpecificSkillC(String value) {
        setAttributeInternal(SPECIFICSKILLC, value);
    }

    /**
     * Gets the attribute value for SpecificSkillD, using the alias name SpecificSkillD.
     * @return the value of SpecificSkillD
     */
    public String getSpecificSkillD() {
        return (String) getAttributeInternal(SPECIFICSKILLD);
    }

    /**
     * Sets <code>value</code> as the attribute value for SpecificSkillD.
     * @param value value to set the SpecificSkillD
     */
    public void setSpecificSkillD(String value) {
        setAttributeInternal(SPECIFICSKILLD, value);
    }

    /**
     * Gets the attribute value for SpecificSkillE, using the alias name SpecificSkillE.
     * @return the value of SpecificSkillE
     */
    public String getSpecificSkillE() {
        return (String) getAttributeInternal(SPECIFICSKILLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SpecificSkillE.
     * @param value value to set the SpecificSkillE
     */
    public void setSpecificSkillE(String value) {
        setAttributeInternal(SPECIFICSKILLE, value);
    }

    /**
     * Gets the attribute value for SpecificSkillF, using the alias name SpecificSkillF.
     * @return the value of SpecificSkillF
     */
    public String getSpecificSkillF() {
        return (String) getAttributeInternal(SPECIFICSKILLF);
    }

    /**
     * Sets <code>value</code> as the attribute value for SpecificSkillF.
     * @param value value to set the SpecificSkillF
     */
    public void setSpecificSkillF(String value) {
        setAttributeInternal(SPECIFICSKILLF, value);
    }

    /**
     * Gets the attribute value for SpecificSkillG, using the alias name SpecificSkillG.
     * @return the value of SpecificSkillG
     */
    public String getSpecificSkillG() {
        return (String) getAttributeInternal(SPECIFICSKILLG);
    }

    /**
     * Sets <code>value</code> as the attribute value for SpecificSkillG.
     * @param value value to set the SpecificSkillG
     */
    public void setSpecificSkillG(String value) {
        setAttributeInternal(SPECIFICSKILLG, value);
    }

    /**
     * Gets the attribute value for HourlyPayMax, using the alias name HourlyPayMax.
     * @return the value of HourlyPayMax
     */
    public BigDecimal getHourlyPayMax() {
        return (BigDecimal) getAttributeInternal(HOURLYPAYMAX);
    }

    /**
     * Sets <code>value</code> as the attribute value for HourlyPayMax.
     * @param value value to set the HourlyPayMax
     */
    public void setHourlyPayMax(BigDecimal value) {
        setAttributeInternal(HOURLYPAYMAX, value);
    }

    /**
     * Gets the attribute value for FixedPayMax, using the alias name FixedPayMax.
     * @return the value of FixedPayMax
     */
    public BigDecimal getFixedPayMax() {
        return (BigDecimal) getAttributeInternal(FIXEDPAYMAX);
    }

    /**
     * Sets <code>value</code> as the attribute value for FixedPayMax.
     * @param value value to set the FixedPayMax
     */
    public void setFixedPayMax(BigDecimal value) {
        setAttributeInternal(FIXEDPAYMAX, value);
    }

    /**
     * Gets the attribute value for DurationMax, using the alias name DurationMax.
     * @return the value of DurationMax
     */
    public BigDecimal getDurationMax() {
        return (BigDecimal) getAttributeInternal(DURATIONMAX);
    }

    /**
     * Sets <code>value</code> as the attribute value for DurationMax.
     * @param value value to set the DurationMax
     */
    public void setDurationMax(BigDecimal value) {
        setAttributeInternal(DURATIONMAX, value);
    }

    /**
     * Gets the attribute value for Status, using the alias name Status.
     * @return the value of Status
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Status.
     * @param value value to set the Status
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for PostJobDateStart, using the alias name PostJobDateStart.
     * @return the value of PostJobDateStart
     */
    public Date getPostJobDateStart() {
        return (Date) getAttributeInternal(POSTJOBDATESTART);
    }

    /**
     * Sets <code>value</code> as the attribute value for PostJobDateStart.
     * @param value value to set the PostJobDateStart
     */
    public void setPostJobDateStart(Date value) {
        setAttributeInternal(POSTJOBDATESTART, value);
    }

    /**
     * Gets the attribute value for PostJobDateEnd, using the alias name PostJobDateEnd.
     * @return the value of PostJobDateEnd
     */
    public Date getPostJobDateEnd() {
        return (Date) getAttributeInternal(POSTJOBDATEEND);
    }

    /**
     * Sets <code>value</code> as the attribute value for PostJobDateEnd.
     * @param value value to set the PostJobDateEnd
     */
    public void setPostJobDateEnd(Date value) {
        setAttributeInternal(POSTJOBDATEEND, value);
    }

    /**
     * Gets the attribute value for LocationCountry, using the alias name LocationCountry.
     * @return the value of LocationCountry
     */
    public String getLocationCountry() {
        return (String) getAttributeInternal(LOCATIONCOUNTRY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LocationCountry.
     * @param value value to set the LocationCountry
     */
    public void setLocationCountry(String value) {
        setAttributeInternal(LOCATIONCOUNTRY, value);
    }

    /**
     * Gets the attribute value for LocationProvince, using the alias name LocationProvince.
     * @return the value of LocationProvince
     */
    public String getLocationProvince() {
        return (String) getAttributeInternal(LOCATIONPROVINCE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LocationProvince.
     * @param value value to set the LocationProvince
     */
    public void setLocationProvince(String value) {
        setAttributeInternal(LOCATIONPROVINCE, value);
    }

    /**
     * Gets the attribute value for LocationCity, using the alias name LocationCity.
     * @return the value of LocationCity
     */
    public String getLocationCity() {
        return (String) getAttributeInternal(LOCATIONCITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LocationCity.
     * @param value value to set the LocationCity
     */
    public void setLocationCity(String value) {
        setAttributeInternal(LOCATIONCITY, value);
    }

    /**
     * Gets the attribute value for CreateBy, using the alias name CreateBy.
     * @return the value of CreateBy
     */
    public String getCreateBy() {
        return (String) getAttributeInternal(CREATEBY);
    }

    /**
     * Gets the attribute value for CreateOn, using the alias name CreateOn.
     * @return the value of CreateOn
     */
    public Date getCreateOn() {
        return (Date) getAttributeInternal(CREATEON);
    }

    /**
     * Gets the attribute value for ModifyBy, using the alias name ModifyBy.
     * @return the value of ModifyBy
     */
    public String getModifyBy() {
        return (String) getAttributeInternal(MODIFYBY);
    }

    /**
     * Gets the attribute value for ModifyOn, using the alias name ModifyOn.
     * @return the value of ModifyOn
     */
    public Timestamp getModifyOn() {
        return (Timestamp) getAttributeInternal(MODIFYON);
    }

    /**
     * Gets the attribute value for Version, using the alias name Version.
     * @return the value of Version
     */
    public Number getVersion() {
        return (Number) getAttributeInternal(VERSION);
    }

    /**
     * Gets the attribute value for StatusDesc, using the alias name StatusDesc.
     * @return the value of StatusDesc
     */
    public String getStatusDesc() {
        return (String) getAttributeInternal(STATUSDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for StatusDesc.
     * @param value value to set the StatusDesc
     */
    public void setStatusDesc(String value) {
        setAttributeInternal(STATUSDESC, value);
    }

    /**
     * Gets the attribute value for IndexSkills, using the alias name IndexSkills.
     * @return the value of IndexSkills
     */
    public String getIndexSkills() {
        return (String) getAttributeInternal(INDEXSKILLS);
    }

    /**
     * Sets <code>value</code> as the attribute value for IndexSkills.
     * @param value value to set the IndexSkills
     */
    public void setIndexSkills(String value) {
        setAttributeInternal(INDEXSKILLS, value);
    }

    /**
     * Gets the attribute value for IndexWorkCategorys, using the alias name IndexWorkCategorys.
     * @return the value of IndexWorkCategorys
     */
    public String getIndexWorkCategorys() {
        return (String) getAttributeInternal(INDEXWORKCATEGORYS);
    }

    /**
     * Sets <code>value</code> as the attribute value for IndexWorkCategorys.
     * @param value value to set the IndexWorkCategorys
     */
    public void setIndexWorkCategorys(String value) {
        setAttributeInternal(INDEXWORKCATEGORYS, value);
    }

    /**
     * Gets the attribute value for IndexLocation, using the alias name IndexLocation.
     * @return the value of IndexLocation
     */
    public String getIndexLocation() {
        return (String) getAttributeInternal(INDEXLOCATION);
    }

    /**
     * Sets <code>value</code> as the attribute value for IndexLocation.
     * @param value value to set the IndexLocation
     */
    public void setIndexLocation(String value) {
        setAttributeInternal(INDEXLOCATION, value);
    }

    /**
     * Gets the attribute value for LocationRegion, using the alias name LocationRegion.
     * @return the value of LocationRegion
     */
    public String getLocationRegion() {
        return (String) getAttributeInternal(LOCATIONREGION);
    }

    /**
     * Sets <code>value</code> as the attribute value for LocationRegion.
     * @param value value to set the LocationRegion
     */
    public void setLocationRegion(String value) {
        setAttributeInternal(LOCATIONREGION, value);
    }

    /**
     * Gets the attribute value for SignBy, using the alias name SignBy.
     * @return the value of SignBy
     */
    public String getSignBy() {
        return (String) getAttributeInternal(SIGNBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for SignBy.
     * @param value value to set the SignBy
     */
    public void setSignBy(String value) {
        setAttributeInternal(SIGNBY, value);
    }

    /**
     * Gets the attribute value for IndexAllMetaInfo, using the alias name IndexAllMetaInfo.
     * @return the value of IndexAllMetaInfo
     */
    public ClobDomain getIndexAllMetaInfo() {
        return (ClobDomain) getAttributeInternal(INDEXALLMETAINFO);
    }

    /**
     * Sets <code>value</code> as the attribute value for IndexAllMetaInfo.
     * @param value value to set the IndexAllMetaInfo
     */
    public void setIndexAllMetaInfo(ClobDomain value) {
        setAttributeInternal(INDEXALLMETAINFO, value);
    }

    /**
     * Gets the attribute value for Rank, using the alias name Rank.
     * @return the value of Rank
     */
    public BigDecimal getRank() {
        return (BigDecimal) getAttributeInternal(RANK);
    }

    /**
     * Sets <code>value</code> as the attribute value for Rank.
     * @param value value to set the Rank
     */
    public void setRank(BigDecimal value) {
        setAttributeInternal(RANK, value);
    }

    /**
     * Gets the attribute value for RankDesc, using the alias name RankDesc.
     * @return the value of RankDesc
     */
    public String getRankDesc() {
        return (String) getAttributeInternal(RANKDESC);
    }

    /**
     * Sets <code>value</code> as the attribute value for RankDesc.
     * @param value value to set the RankDesc
     */
    public void setRankDesc(String value) {
        setAttributeInternal(RANKDESC, value);
    }

    /**
     * Gets the attribute value for ApplyCount, using the alias name ApplyCount.
     * @return the value of ApplyCount
     */
    public BigDecimal getApplyCount() {
        return (BigDecimal) getAttributeInternal(APPLYCOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for ApplyCount.
     * @param value value to set the ApplyCount
     */
    public void setApplyCount(BigDecimal value) {
        setAttributeInternal(APPLYCOUNT, value);
    }

    /**
     * @param uuid key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(String uuid) {
        return new Key(new Object[] { uuid });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("com.lance.model.eo.PostJobsEO");
    }
    
    @Override
    public void lock() {
        try {
            super.lock();
        } catch (RowInconsistentException e) {
            refresh(REFRESH_WITH_DB_ONLY_IF_UNCHANGED | REFRESH_CONTAINEES);
            super.lock();
        }
    }
}

