package com.lance.model.vo;

import com.zngh.platform.front.core.model.BaseViewObjectImpl;

// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Nov 15 09:12:15 CST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PostJobDiscussVOImpl extends BaseViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public PostJobDiscussVOImpl() {
    }

    /**
     * Returns the variable value for pId.
     * @return variable value for pId
     */
    public String getpId() {
        return (String) ensureVariableManager().getVariableValue("pId");
    }

    /**
     * Sets <code>value</code> for variable pId.
     * @param value value to bind as pId
     */
    public void setpId(String value) {
        ensureVariableManager().setVariableValue("pId", value);
    }

    /**
     * Returns the variable value for pJobId.
     * @return variable value for pJobId
     */
    public String getpJobId() {
        return (String) ensureVariableManager().getVariableValue("pJobId");
    }

    /**
     * Sets <code>value</code> for variable pJobId.
     * @param value value to bind as pJobId
     */
    public void setpJobId(String value) {
        ensureVariableManager().setVariableValue("pJobId", value);
    }

    /**
     * Returns the variable value for pCreator.
     * @return variable value for pCreator
     */
    public String getpCreator() {
        return (String) ensureVariableManager().getVariableValue("pCreator");
    }

    /**
     * Sets <code>value</code> for variable pCreator.
     * @param value value to bind as pCreator
     */
    public void setpCreator(String value) {
        ensureVariableManager().setVariableValue("pCreator", value);
    }

    /**
     * Returns the variable value for applyflag.
     * @return variable value for applyflag
     */
    public String getapplyflag() {
        return (String) ensureVariableManager().getVariableValue("applyflag");
    }

    /**
     * Sets <code>value</code> for variable applyflag.
     * @param value value to bind as applyflag
     */
    public void setapplyflag(String value) {
        ensureVariableManager().setVariableValue("applyflag", value);
    }

    /**
     * Returns the variable value for uName.
     * @return variable value for uName
     */
    public String getuName() {
        return (String) ensureVariableManager().getVariableValue("uName");
    }

    /**
     * Sets <code>value</code> for variable uName.
     * @param value value to bind as uName
     */
    public void setuName(String value) {
        ensureVariableManager().setVariableValue("uName", value);
    }
}

