package com.lance.model.vo;

import com.zngh.platform.front.core.model.BaseViewObjectImpl;

// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jun 08 09:45:46 CST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RetrievePasswordVOImpl extends BaseViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public RetrievePasswordVOImpl() {
    }

    /**
     * Returns the variable value for puid.
     * @return variable value for puid
     */
    public String getpuid() {
        return (String) ensureVariableManager().getVariableValue("puid");
    }

    /**
     * Sets <code>value</code> for variable puid.
     * @param value value to bind as puid
     */
    public void setpuid(String value) {
        ensureVariableManager().setVariableValue("puid", value);
    }
}

