package com.lance.model.vo;

import com.zngh.platform.front.core.model.BaseEntityImpl;
import com.zngh.platform.front.core.model.BaseViewRowImpl;

import java.sql.Timestamp;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jun 08 09:45:45 CST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RetrievePasswordVORowImpl extends BaseViewRowImpl {

    public static final int ENTITY_RETRIEVEPASSWORDEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Uuid,
        CreateOn,
        OreateBy,
        UserName;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int UUID = AttributesEnum.Uuid.index();
    public static final int CREATEON = AttributesEnum.CreateOn.index();
    public static final int OREATEBY = AttributesEnum.OreateBy.index();
    public static final int USERNAME = AttributesEnum.UserName.index();

    /**
     * This is the default constructor (do not remove).
     */
    public RetrievePasswordVORowImpl() {
    }

    /**
     * Gets RetrievePasswordEO entity object.
     * @return the RetrievePasswordEO
     */
    public BaseEntityImpl getRetrievePasswordEO() {
        return (BaseEntityImpl) getEntity(ENTITY_RETRIEVEPASSWORDEO);
    }

    /**
     * Gets the attribute value for UUID using the alias name Uuid.
     * @return the UUID
     */
    public String getUuid() {
        return (String) getAttributeInternal(UUID);
    }

    /**
     * Sets <code>value</code> as attribute value for UUID using the alias name Uuid.
     * @param value value to set the UUID
     */
    public void setUuid(String value) {
        setAttributeInternal(UUID, value);
    }

    /**
     * Gets the attribute value for CREATE_ON using the alias name CreateOn.
     * @return the CREATE_ON
     */
    public Timestamp getCreateOn() {
        return (Timestamp) getAttributeInternal(CREATEON);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATE_ON using the alias name CreateOn.
     * @param value value to set the CREATE_ON
     */
    public void setCreateOn(Timestamp value) {
        setAttributeInternal(CREATEON, value);
    }

    /**
     * Gets the attribute value for OREATE_BY using the alias name OreateBy.
     * @return the OREATE_BY
     */
    public String getOreateBy() {
        return (String) getAttributeInternal(OREATEBY);
    }

    /**
     * Sets <code>value</code> as attribute value for OREATE_BY using the alias name OreateBy.
     * @param value value to set the OREATE_BY
     */
    public void setOreateBy(String value) {
        setAttributeInternal(OREATEBY, value);
    }

    /**
     * Gets the attribute value for USER_NAME using the alias name UserName.
     * @return the USER_NAME
     */
    public String getUserName() {
        return (String) getAttributeInternal(USERNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for USER_NAME using the alias name UserName.
     * @param value value to set the USER_NAME
     */
    public void setUserName(String value) {
        setAttributeInternal(USERNAME, value);
    }
}

