package com.lance.model.vo;

import com.zngh.platform.front.core.model.BaseEntityImpl;
import com.zngh.platform.front.core.model.BaseViewRowImpl;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.RowIterator;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 09 16:28:43 CST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SkillSuperTypeVORowImpl extends BaseViewRowImpl {
    public static final int ENTITY_SKILLSUPERTYPEEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Uuid,
        Name,
        NameCn,
        Description,
        CreateBy,
        CreateOn,
        ModifyBy,
        ModifyOn,
        Version,
        CreateByName,
        ModifyByName,
        Skills;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int UUID = AttributesEnum.Uuid.index();
    public static final int NAME = AttributesEnum.Name.index();
    public static final int NAMECN = AttributesEnum.NameCn.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int CREATEBY = AttributesEnum.CreateBy.index();
    public static final int CREATEON = AttributesEnum.CreateOn.index();
    public static final int MODIFYBY = AttributesEnum.ModifyBy.index();
    public static final int MODIFYON = AttributesEnum.ModifyOn.index();
    public static final int VERSION = AttributesEnum.Version.index();
    public static final int CREATEBYNAME = AttributesEnum.CreateByName.index();
    public static final int MODIFYBYNAME = AttributesEnum.ModifyByName.index();
    public static final int SKILLS = AttributesEnum.Skills.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SkillSuperTypeVORowImpl() {
    }

    /**
     * Gets SkillSuperTypeEO entity object.
     * @return the SkillSuperTypeEO
     */
    public BaseEntityImpl getSkillSuperTypeEO() {
        return (BaseEntityImpl) getEntity(ENTITY_SKILLSUPERTYPEEO);
    }

    /**
     * Gets the attribute value for UUID using the alias name Uuid.
     * @return the UUID
     */
    public String getUuid() {
        return (String) getAttributeInternal(UUID);
    }

    /**
     * Sets <code>value</code> as attribute value for UUID using the alias name Uuid.
     * @param value value to set the UUID
     */
    public void setUuid(String value) {
        setAttributeInternal(UUID, value);
    }

    /**
     * Gets the attribute value for NAME using the alias name Name.
     * @return the NAME
     */
    public String getName() {
        return (String) getAttributeInternal(NAME);
    }

    /**
     * Sets <code>value</code> as attribute value for NAME using the alias name Name.
     * @param value value to set the NAME
     */
    public void setName(String value) {
        setAttributeInternal(NAME, value);
    }

    /**
     * Gets the attribute value for NAME_CN using the alias name NameCn.
     * @return the NAME_CN
     */
    public String getNameCn() {
        return (String) getAttributeInternal(NAMECN);
    }

    /**
     * Sets <code>value</code> as attribute value for NAME_CN using the alias name NameCn.
     * @param value value to set the NAME_CN
     */
    public void setNameCn(String value) {
        setAttributeInternal(NAMECN, value);
    }

    /**
     * Gets the attribute value for DESCRIPTION using the alias name Description.
     * @return the DESCRIPTION
     */
    public String getDescription() {
        return (String) getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for DESCRIPTION using the alias name Description.
     * @param value value to set the DESCRIPTION
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the attribute value for CREATE_BY using the alias name CreateBy.
     * @return the CREATE_BY
     */
    public String getCreateBy() {
        return (String) getAttributeInternal(CREATEBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATE_BY using the alias name CreateBy.
     * @param value value to set the CREATE_BY
     */
    public void setCreateBy(String value) {
        setAttributeInternal(CREATEBY, value);
    }

    /**
     * Gets the attribute value for CREATE_ON using the alias name CreateOn.
     * @return the CREATE_ON
     */
    public Timestamp getCreateOn() {
        return (Timestamp) getAttributeInternal(CREATEON);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATE_ON using the alias name CreateOn.
     * @param value value to set the CREATE_ON
     */
    public void setCreateOn(Timestamp value) {
        setAttributeInternal(CREATEON, value);
    }

    /**
     * Gets the attribute value for MODIFY_BY using the alias name ModifyBy.
     * @return the MODIFY_BY
     */
    public String getModifyBy() {
        return (String) getAttributeInternal(MODIFYBY);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFY_BY using the alias name ModifyBy.
     * @param value value to set the MODIFY_BY
     */
    public void setModifyBy(String value) {
        setAttributeInternal(MODIFYBY, value);
    }

    /**
     * Gets the attribute value for MODIFY_ON using the alias name ModifyOn.
     * @return the MODIFY_ON
     */
    public Timestamp getModifyOn() {
        return (Timestamp) getAttributeInternal(MODIFYON);
    }

    /**
     * Sets <code>value</code> as attribute value for MODIFY_ON using the alias name ModifyOn.
     * @param value value to set the MODIFY_ON
     */
    public void setModifyOn(Timestamp value) {
        setAttributeInternal(MODIFYON, value);
    }

    /**
     * Gets the attribute value for VERSION using the alias name Version.
     * @return the VERSION
     */
    public BigDecimal getVersion() {
        return (BigDecimal) getAttributeInternal(VERSION);
    }

    /**
     * Sets <code>value</code> as attribute value for VERSION using the alias name Version.
     * @param value value to set the VERSION
     */
    public void setVersion(BigDecimal value) {
        setAttributeInternal(VERSION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CreateByName.
     * @return the CreateByName
     */
    public String getCreateByName() {
        return (String) getAttributeInternal(CREATEBYNAME);
    }

    /**
     * Gets the attribute value for the calculated attribute ModifyByName.
     * @return the ModifyByName
     */
    public String getModifyByName() {
        return (String) getAttributeInternal(MODIFYBYNAME);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link Skills.
     */
    public RowIterator getSkills() {
        return (RowIterator) getAttributeInternal(SKILLS);
    }
}

